import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({apiKey: process.env.API_KEY!});

/**
 * Generates a high-quality, photorealistic image for a given listing.
 * @param title The title of the listing (e.g., "Adventure Double Kayak").
 * @param locationContext A string describing the location (e.g., "on a calm lake in Bariloche").
 * @returns A promise that resolves to a base64 encoded image string (e.g., "data:image/png;base64,...").
 */
export const generateImageForListing = async (title: string, locationContext: string): Promise<string> => {
    try {
        const prompt = `Professional, photorealistic product shot of a "${title}". The item should be clean, appealing, and centrally featured. The background should be scenic, appropriate for the item, evoking a sense of adventure, such as ${locationContext}. The lighting should be bright and natural, as if taken by a professional photographer for a high-end rental marketplace.`;
        
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '3:2', // A good ratio for product cards
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image for listing with Gemini:", error);
        // Return a placeholder or throw the error to be handled by the caller
        throw error;
    }
};
