
import { Listing, ListingCategory, User } from '../types';
import { format } from 'date-fns';

export enum ContractType {
    BAREBOAT = "Bareboat Charter Agreement",
    HIGH_RISK_WAIVER = "Liability Waiver & Assumption of Risk",
    STANDARD_RENTAL = "Standard Equipment Rental Agreement"
}

export class LegalService {

    public static getContractType(category: ListingCategory): ContractType {
        if (category === ListingCategory.BOATS) {
            return ContractType.BAREBOAT;
        }
        if (category === ListingCategory.UTVS || category === ListingCategory.MOTORCYCLES || category === ListingCategory.WATER_SPORTS) {
            // Simplified check: Assume Jet Skis (Water Sports) fall here for now
            return ContractType.HIGH_RISK_WAIVER;
        }
        return ContractType.STANDARD_RENTAL;
    }

    public static generateContractHtml(listing: Listing, renter: User, startDate: Date, endDate: Date, totalPrice: number): string {
        const contractType = this.getContractType(listing.category);
        const dateStr = format(new Date(), 'MMMM do, yyyy');
        const startStr = format(startDate, 'MMM dd, yyyy');
        const endStr = format(endDate, 'MMM dd, yyyy');

        const header = `
            <div class="text-center mb-6">
                <h1 class="text-xl font-bold uppercase">${contractType}</h1>
                <p class="text-sm text-gray-500">Generated by Goodslister Legal Center on ${dateStr}</p>
            </div>
            <div class="mb-4 p-4 bg-gray-50 rounded border text-sm">
                <p><strong>LESSOR (Owner):</strong> ${listing.owner.name}</p>
                <p><strong>LESSEE (Renter):</strong> ${renter.name}</p>
                <p><strong>ITEM:</strong> ${listing.title} (Category: ${listing.category})</p>
                <p><strong>RENTAL PERIOD:</strong> ${startStr} to ${endStr}</p>
            </div>
        `;

        let body = '';

        switch (contractType) {
            case ContractType.BAREBOAT:
                body = `
                    <h3 class="font-bold mt-4">1. DEMISE CHARTER</h3>
                    <p>The Renter acknowledges that they have full command, possession, and control of the vessel for the duration of the rental period. The Owner provides no crew.</p>
                    
                    <h3 class="font-bold mt-4">2. SEAWORTHINESS</h3>
                    <p>The Renter warrants that they are competent to operate the vessel. The Owner warrants the vessel is seaworthy at the time of handover.</p>
                    
                    <h3 class="font-bold mt-4">3. NAVIGATION LIMITS</h3>
                    <p>The vessel shall be used only within the coastal waters of ${listing.location.city}, ${listing.location.state}.</p>
                `;
                break;

            case ContractType.HIGH_RISK_WAIVER:
                body = `
                    <h3 class="font-bold mt-4 text-red-700">1. ASSUMPTION OF RISK</h3>
                    <p>The Renter acknowledges that operating a ${listing.category} involves inherent risks, including bodily injury or death. The Renter voluntarily assumes all such risks.</p>
                    
                    <h3 class="font-bold mt-4">2. SAFETY BRIEFING</h3>
                    <p>The Renter confirms they will receive a safety briefing from the Owner regarding the operation of the vehicle/craft before use.</p>
                    
                    <h3 class="font-bold mt-4">3. HELMETS & SAFETY GEAR</h3>
                    <p>The Renter agrees to wear all legally required safety equipment (helmets, life vests) at all times.</p>
                `;
                break;

            default: // STANDARD
                body = `
                    <h3 class="font-bold mt-4">1. CONDITION OF EQUIPMENT</h3>
                    <p>The Renter acknowledges receiving the equipment in good working order and agrees to return it in the same condition, ordinary wear and tear excepted.</p>
                    
                    <h3 class="font-bold mt-4">2. RESPONSIBILITY FOR LOSS</h3>
                    <p>The Renter is responsible for the full replacement cost of the equipment if lost or stolen during the rental period.</p>
                `;
                break;
        }

        const commonClauses = `
            <h3 class="font-bold mt-4">4. SECURITY DEPOSIT</h3>
            <p>A security deposit of <strong>$${listing.securityDeposit || 0}</strong> is held by Goodslister to cover potential damages.</p>
            
            <h3 class="font-bold mt-4">5. INDEMNIFICATION</h3>
            <p>The Renter agrees to indemnify and hold harmless the Owner and Goodslister from any claims arising out of the use of the rented item.</p>
        `;

        return header + body + commonClauses;
    }
}
