import type { VercelRequest, VercelResponse } from '@vercel/node';
import { sql } from '@vercel/postgres';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);
const FROM_ADDRESS = 'Goodslister <noreply@goodslister.com>';

// This cron runs daily at 8am UTC (vercel.json: "0 8 * * *")
// It finds bookings that start TOMORROW and sends pickup reminders.
export default async function handler(
  request: VercelRequest,
    response: VercelResponse,
    ) {
      // Only allow GET (Vercel cron) or POST with valid CRON_SECRET
        const authHeader = request.headers['authorization'];
          const secret = process.env.CRON_SECRET;

            if (
                request.method === 'POST' &&
                    authHeader !== `Bearer ${secret}`
                      ) {
                          return response.status(401).json({ error: 'Unauthorized' });
                            }

                              if (request.method !== 'GET' && request.method !== 'POST') {
                                  return response.status(405).json({ error: 'Method not allowed' });
                                    }

                                      if (!process.env.POSTGRES_URL) {
                                          return response.status(200).json({ message: 'No database configured, skipping cron' });
                                            }

                                              if (!process.env.RESEND_API_KEY) {
                                                  return response.status(200).json({ message: 'No email configured, skipping cron' });
                                                    }

                                                      try {
                                                          // Get tomorrow's date in YYYY-MM-DD format
                                                              const tomorrow = new Date();
                                                                  tomorrow.setDate(tomorrow.getDate() + 1);
                                                                      const tomorrowStr = tomorrow.toISOString().split('T')[0];

                                                                          // Query bookings that start tomorrow and are confirmed/active
                                                                              const { rows: bookings } = await sql`
                                                                                    SELECT
                                                                                            b.id AS booking_id,
                                                                                                    b.listing_title,
                                                                                                            b.start_date,
                                                                                                                    b.end_date,
                                                                                                                            u.name AS renter_name,
                                                                                                                                    u.email AS renter_email
                                                                                                                                          FROM bookings b
                                                                                                                                                JOIN users u ON u.id = b.renter_id
                                                                                                                                                      WHERE DATE(b.start_date) = ${tomorrowStr}
                                                                                                                                                              AND b.status IN ('confirmed', 'pending', 'active')
                                                                                                                                                                      AND u.email IS NOT NULL
                                                                                                                                                                          `;
                                                                                                                                                                          
                                                                                                                                                                              if (bookings.length === 0) {
                                                                                                                                                                                    return response.status(200).json({
                                                                                                                                                                                            message: `No pickups tomorrow (${tomorrowStr})`,
                                                                                                                                                                                                    sent: 0,
                                                                                                                                                                                                          });
                                                                                                                                                                                                              }
                                                                                                                                                                                                              
                                                                                                                                                                                                                  let sent = 0;
                                                                                                                                                                                                                      const errors: string[] = [];
                                                                                                                                                                                                                      
                                                                                                                                                                                                                          for (const booking of bookings) {
                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                        const startFormatted = new Date(booking.start_date).toLocaleDateString('en-US', {
                                                                                                                                                                                                                                                  weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                  const endFormatted = booking.end_date
                                                                                                                                                                                                                                                                            ? new Date(booking.end_date).toLocaleDateString('en-US', {
                                                                                                                                                                                                                                                                                          month: 'long', day: 'numeric', year: 'numeric',
                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                : '—';
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        // Build email HTML (reusing the same style as send-email.ts)
                                                                                                                                                                                                                                                                                                                                const html = buildReminderEmail(
                                                                                                                                                                                                                                                                                                                                          booking.renter_name,
                                                                                                                                                                                                                                                                                                                                                    booking.listing_title,
                                                                                                                                                                                                                                                                                                                                                              startFormatted,
                                                                                                                                                                                                                                                                                                                                                                        endFormatted,
                                                                                                                                                                                                                                                                                                                                                                                  booking.booking_id,
                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                  await resend.emails.send({
                                                                                                                                                                                                                                                                                                                                                                                                            from: FROM_ADDRESS,
                                                                                                                                                                                                                                                                                                                                                                                                                      to: [booking.renter_email],
                                                                                                                                                                                                                                                                                                                                                                                                                                subject: `Reminder: Pick up "${booking.listing_title}" tomorrow`,
                                                                                                                                                                                                                                                                                                                                                                                                                                          html,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                          sent++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        errors.push(`${booking.booking_id}: ${String(err)}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`Pickup reminder cron: ${sent}/${bookings.length} emails sent for ${tomorrowStr}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return response.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                date: tomorrowStr,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      total: bookings.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  errors,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Pickup reminder cron error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return response.status(500).json({ error: 'Cron job failed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function buildReminderEmail(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      listingTitle: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startDate: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          endDate: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bookingId: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const appUrl = 'https://www.goodslister.com';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const brand = '#1e3a5f';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const accent = '#2563eb';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return `<!DOCTYPE html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <html lang="en">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/></head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <body style="margin:0;padding:0;background:#f4f6fb;font-family:Arial,sans-serif;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6fb;padding:32px 0;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr><td align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 16px rgba(0,0,0,0.08);max-width:600px;width:100%;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr><td style="background:${brand};padding:28px 40px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 style="margin:0;color:#fff;font-size:26px;font-weight:700;letter-spacing:1px;">GOODSLISTER</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style="margin:6px 0 0;color:#93c5fd;font-size:13px;">Adventure Rental Marketplace</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style="padding:40px 40px 32px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 style="margin:0 0 8px;color:${brand};font-size:22px;">Pick-up reminder ⏰</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style="color:#475569;font-size:15px;line-height:1.7;margin:0 0 24px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Hi ${name}, just a friendly reminder that your rental pick-up is <strong>tomorrow</strong>!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <table cellpadding="0" cellspacing="0" style="width:100%;background:#f0f7ff;border-radius:8px;padding:20px 24px;margin-bottom:24px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style="padding:8px 0;color:#64748b;font-size:14px;width:160px;">Item</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td style="padding:8px 0;color:#1e293b;font-size:14px;font-weight:600;">${listingTitle}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td style="padding:8px 0;color:#64748b;font-size:14px;">Pick-up date</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td style="padding:8px 0;color:#1e293b;font-size:14px;font-weight:600;">${startDate}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style="padding:8px 0;color:#64748b;font-size:14px;">Return date</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td style="padding:8px 0;color:#1e293b;font-size:14px;font-weight:600;">${endDate}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td style="padding:8px 0;color:#64748b;font-size:14px;">Booking ID</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td style="padding:8px 0;color:#1e293b;font-size:14px;font-weight:600;">${bookingId}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style="color:#475569;font-size:14px;line-height:1.6;margin:0;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Make sure you know the pick-up location and have your booking confirmation ready. Have a great adventure! 🎒
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="${appUrl}" style="display:inline-block;margin-top:24px;padding:14px 32px;background:${accent};color:#fff;text-decoration:none;border-radius:8px;font-size:15px;font-weight:600;">View Booking Details</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr><td style="background:#f8fafc;padding:24px 40px;text-align:center;border-top:1px solid #e2e8f0;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style="margin:0;color:#94a3b8;font-size:12px;">© 2026 Goodslister · <a href="${appUrl}" style="color:${accent};text-decoration:none;">goodslister.com</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </html>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
